services:
  casdoor:
    restart: always
    image: 'casbin/casdoor:latest'
    container_name: casdoor
    env_file:
      - app.conf
    environment:
      RUNNING_IN_DOCKER: "true"
    depends_on:
      - db_casdoor
    ports:
      - 9080:8000

  db_casdoor:
    image: postgres:14.11
    container_name: db_casdoor
    env_file:
      - app.conf
    working_dir: /
    volumes:
      - db-volume-casdoor:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  broker:
    image: mochimqtt/server:latest
    ports:
      - "1883:1883"

volumes:
  db-volume-casdoor: {}