output   = "models"
wipe     = true
no-tests = false
add-enum-types = true

[psql]
  dbname = "messagedb"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  sslmode = "disable"
  blacklist = ["migrations", "other"]